from django.urls import path
from .views import (
    EspecialidadeListView, 
    EspecialidadeDetailView, 
    EspecialidadeCreateView, 
    EspecialidadeUpdateView, 
    EspecialidadeDeleteView,
    MedicoListView,
    MedicoDetailView,
    MedicoCreateView,
    MedicoUpdateView,
    MedicoDeleteView,
    PacienteListView,
    PacienteDetailView,
    PacienteCreateView,
    PacienteUpdateView,
    PacienteDeleteView,
    ConsultaListView,
    ConsultaDetailView,
    ConsultaCreateView,
    ConsultaUpdateView,
    ConsultaDeleteView,
)

urlpatterns = [
    path('especialidades/', EspecialidadeListView.as_view(), name='especialidade_list'),
    path('especialidades/<int:pk>/', EspecialidadeDetailView.as_view(), name='especialidade_detail'),
    path('especialidades/novo/', EspecialidadeCreateView.as_view(), name='especialidade_create'),
    path('especialidades/<int:pk>/editar/', EspecialidadeUpdateView.as_view(), name='especialidade_update'),
    path('especialidades/<int:pk>/excluir/', EspecialidadeDeleteView.as_view(), name='especialidade_delete'),   
    path('medicos/', MedicoListView.as_view(), name='medico_list'),
    path('medicos/<int:pk>/', MedicoDetailView.as_view(), name='medico_detail'),
    path('medicos/novo/', MedicoCreateView.as_view(), name='medico_create'),
    path('medicos/<int:pk>/editar/', MedicoUpdateView.as_view(), name='medico_update'),
    path('medicos/<int:pk>/excluir/', MedicoDeleteView.as_view(), name='medico_delete'),
    path('pacientes/', PacienteListView.as_view(), name='paciente_list'),
    path('pacientes/<int:pk>/', PacienteDetailView.as_view(), name='paciente_detail'),
    path('pacientes/novo/', PacienteCreateView.as_view(), name='paciente_create'),
    path('pacientes/<int:pk>/editar/', PacienteUpdateView.as_view(), name='paciente_update'),
    path('pacientes/<int:pk>/excluir/', PacienteDeleteView.as_view(), name='paciente_delete'),
    path('consultas/', ConsultaListView.as_view(), name='consulta_list'),
    path('consultas/<int:pk>/', ConsultaDetailView.as_view(), name='consulta_detail'),
    path('consultas/novo/', ConsultaCreateView.as_view(), name='consulta_create'),
    path('consultas/<int:pk>/editar/', ConsultaUpdateView.as_view(), name='consulta_update'),
    path('consultas/<int:pk>/excluir/', ConsultaDeleteView.as_view(), name='consulta_delete'),
]
    