# Generated by Django 5.2.4 on 2025-07-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='dias_trabalho',
            field=models.CharField(default='segunda,terca,quarta,quinta,sexta', help_text='Dias da semana que o médico trabalha (separados por vírgula)', max_length=200),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_fim',
            field=models.TimeField(default='18:00', help_text='Horário de fim do expediente'),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_inicio',
            field=models.TimeField(default='09:00', help_text='Horário de início do expediente'),
        ),
    ]
