# Generated by Django 5.2.4 on 2025-07-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_medico_dias_trabalho_medico_hora_fim_and_more'),
    ]

    operations = [
    ]
